plugins {
    id 'java'
}

group = 'com.red.retrovein'
version = '0.1.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

compileJava {
	options.release.set(8)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
