# Mapping
mappingClasses=true
mappingFields=true
mappingMethods=true
mappingLocalVariables=true
mappingEnums=true

# Packages
packageRemap=true

# Transformers
transformerAsmRemapping=true

# Processing
coreThreads=4
